// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package com_ta04_srv_auth

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                     int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName              string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName               string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Username               string   `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Password               string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	EmailAddress           string   `protobuf:"bytes,6,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	PhoneNumber            string   `protobuf:"bytes,7,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	DateOfBirth            string   `protobuf:"bytes,8,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Address                string   `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Role                   string   `protobuf:"bytes,10,opt,name=role,proto3" json:"role,omitempty"`
	CreditCardNumber       string   `protobuf:"bytes,11,opt,name=credit_card_number,json=creditCardNumber,proto3" json:"credit_card_number,omitempty"`
	CreditCardType         string   `protobuf:"bytes,12,opt,name=credit_card_type,json=creditCardType,proto3" json:"credit_card_type,omitempty"`
	CreditCardExpiredMonth string   `protobuf:"bytes,13,opt,name=credit_card_expired_month,json=creditCardExpiredMonth,proto3" json:"credit_card_expired_month,omitempty"`
	CreditCardExpiredYear  string   `protobuf:"bytes,14,opt,name=credit_card_expired_year,json=creditCardExpiredYear,proto3" json:"credit_card_expired_year,omitempty"`
	CreditCardCvv          string   `protobuf:"bytes,15,opt,name=credit_card_cvv,json=creditCardCvv,proto3" json:"credit_card_cvv,omitempty"`
	Status                 bool     `protobuf:"varint,16,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetEmailAddress() string {
	if m != nil {
		return m.EmailAddress
	}
	return ""
}

func (m *User) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *User) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *User) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetCreditCardNumber() string {
	if m != nil {
		return m.CreditCardNumber
	}
	return ""
}

func (m *User) GetCreditCardType() string {
	if m != nil {
		return m.CreditCardType
	}
	return ""
}

func (m *User) GetCreditCardExpiredMonth() string {
	if m != nil {
		return m.CreditCardExpiredMonth
	}
	return ""
}

func (m *User) GetCreditCardExpiredYear() string {
	if m != nil {
		return m.CreditCardExpiredYear
	}
	return ""
}

func (m *User) GetCreditCardCvv() string {
	if m != nil {
		return m.CreditCardCvv
	}
	return ""
}

func (m *User) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

type Request struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

type Response struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Users                []*User  `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *Response) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *Response) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Token struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Valid                bool     `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Errors               []*Error `protobuf:"bytes,3,rep,name=errors,proto3" json:"errors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Token) Reset()         { *m = Token{} }
func (m *Token) String() string { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()    {}
func (*Token) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{3}
}

func (m *Token) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Token.Unmarshal(m, b)
}
func (m *Token) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Token.Marshal(b, m, deterministic)
}
func (m *Token) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Token.Merge(m, src)
}
func (m *Token) XXX_Size() int {
	return xxx_messageInfo_Token.Size(m)
}
func (m *Token) XXX_DiscardUnknown() {
	xxx_messageInfo_Token.DiscardUnknown(m)
}

var xxx_messageInfo_Token proto.InternalMessageInfo

func (m *Token) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *Token) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *Token) GetErrors() []*Error {
	if m != nil {
		return m.Errors
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{4}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "com.ta04.srv.auth.User")
	proto.RegisterType((*Request)(nil), "com.ta04.srv.auth.Request")
	proto.RegisterType((*Response)(nil), "com.ta04.srv.auth.Response")
	proto.RegisterType((*Token)(nil), "com.ta04.srv.auth.Token")
	proto.RegisterType((*Error)(nil), "com.ta04.srv.auth.Error")
}

func init() {
	proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874)
}

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x86, 0x49, 0x9a, 0xa4, 0xf6, 0xa4, 0x69, 0xcb, 0x08, 0xca, 0x52, 0x84, 0x14, 0x8c, 0x84,
	0x22, 0x01, 0x56, 0x55, 0x90, 0x10, 0x42, 0x1c, 0x4a, 0xd5, 0x23, 0x45, 0x32, 0x05, 0x89, 0x93,
	0xb5, 0xf5, 0x4e, 0x15, 0x8b, 0xd8, 0x6b, 0x76, 0xd7, 0x86, 0x3e, 0x06, 0x37, 0x1e, 0x83, 0x47,
	0x44, 0x3b, 0x8e, 0xd5, 0x48, 0x4d, 0x7b, 0xe0, 0x94, 0xfd, 0xff, 0xff, 0x9b, 0xcc, 0xae, 0x3d,
	0x6b, 0x00, 0x59, 0xbb, 0x79, 0x5c, 0x19, 0xed, 0x34, 0xde, 0xcd, 0x74, 0x11, 0x3b, 0x79, 0xf0,
	0x3a, 0xb6, 0xa6, 0x89, 0x7d, 0x10, 0xfd, 0x1d, 0xc0, 0xe0, 0x8b, 0x25, 0x83, 0xdb, 0xd0, 0xcf,
	0x95, 0xe8, 0x4d, 0x7b, 0xb3, 0x61, 0xd2, 0xcf, 0x15, 0x3e, 0x06, 0xb8, 0xc8, 0x8d, 0x75, 0x69,
	0x29, 0x0b, 0x12, 0xfd, 0x69, 0x6f, 0x16, 0x26, 0x21, 0x3b, 0xa7, 0xb2, 0x20, 0x7c, 0x04, 0xe1,
	0x42, 0x76, 0xe9, 0x06, 0xa7, 0x81, 0x37, 0x38, 0xdc, 0x87, 0xa0, 0xb6, 0x64, 0x38, 0x1b, 0xb4,
	0x59, 0xa7, 0x7d, 0x56, 0x49, 0x6b, 0x7f, 0x6a, 0xa3, 0xc4, 0xb0, 0xcd, 0x3a, 0x8d, 0x4f, 0x61,
	0x42, 0x85, 0xcc, 0x17, 0xa9, 0x54, 0xca, 0x90, 0xb5, 0x62, 0xc4, 0xc0, 0x16, 0x9b, 0x47, 0xad,
	0x87, 0x4f, 0x60, 0xab, 0x9a, 0xeb, 0x92, 0xd2, 0xb2, 0x2e, 0xce, 0xc9, 0x88, 0x4d, 0x66, 0xc6,
	0xec, 0x9d, 0xb2, 0x85, 0x11, 0x4c, 0x94, 0x74, 0x94, 0xea, 0x8b, 0xf4, 0x3c, 0x37, 0x6e, 0x2e,
	0x82, 0x96, 0xf1, 0xe6, 0xa7, 0x8b, 0x0f, 0xde, 0x42, 0x01, 0x9b, 0x5d, 0x97, 0x90, 0xd3, 0x4e,
	0x22, 0xc2, 0xc0, 0xe8, 0x05, 0x09, 0x60, 0x9b, 0xd7, 0xf8, 0x02, 0x30, 0x33, 0xa4, 0x72, 0x97,
	0x66, 0xd2, 0xa8, 0xae, 0xf5, 0x98, 0x89, 0xdd, 0x36, 0x39, 0x96, 0x46, 0x2d, 0xfb, 0xcf, 0x60,
	0x77, 0x95, 0x76, 0x97, 0x15, 0x89, 0x2d, 0x66, 0xb7, 0xaf, 0xd8, 0xb3, 0xcb, 0x8a, 0xf0, 0x2d,
	0x3c, 0x5c, 0x25, 0xe9, 0x57, 0x95, 0x1b, 0x52, 0x69, 0xa1, 0x4b, 0x37, 0x17, 0x13, 0x2e, 0xd9,
	0xbb, 0x2a, 0x39, 0x69, 0xe3, 0x8f, 0x3e, 0xc5, 0x37, 0x20, 0xd6, 0x95, 0x5e, 0x92, 0x34, 0x62,
	0x9b, 0x2b, 0xef, 0x5f, 0xab, 0xfc, 0x46, 0xd2, 0xe0, 0x33, 0xd8, 0x59, 0x2d, 0xcc, 0x9a, 0x46,
	0xec, 0x30, 0x3f, 0xb9, 0xe2, 0x8f, 0x9b, 0x06, 0xf7, 0x60, 0x64, 0x9d, 0x74, 0xb5, 0x15, 0xbb,
	0xd3, 0xde, 0x2c, 0x48, 0x96, 0x2a, 0x0a, 0x61, 0x33, 0xa1, 0x1f, 0x35, 0x59, 0x17, 0xfd, 0xe9,
	0x41, 0x90, 0x90, 0xad, 0x74, 0x69, 0x09, 0x9f, 0xc3, 0xc0, 0xbf, 0x65, 0x9e, 0xa1, 0xf1, 0xe1,
	0x83, 0xf8, 0xda, 0xb0, 0xc5, 0x7e, 0xd0, 0x12, 0x86, 0xf0, 0x25, 0x0c, 0xfd, 0xaf, 0x15, 0xfd,
	0xe9, 0xc6, 0x6d, 0x74, 0x4b, 0xe1, 0x01, 0x8c, 0xc8, 0x18, 0x6d, 0xac, 0xd8, 0x60, 0x5e, 0xac,
	0xe1, 0x4f, 0x3c, 0x90, 0x2c, 0xb9, 0x88, 0x60, 0x78, 0xa6, 0xbf, 0x53, 0x89, 0xf7, 0x60, 0xe8,
	0xfc, 0x82, 0xf7, 0x15, 0x26, 0xad, 0xf0, 0x6e, 0x23, 0x17, 0xb9, 0xe2, 0xc9, 0x0e, 0x92, 0x56,
	0xfc, 0x47, 0x9b, 0xf7, 0x30, 0x64, 0xc3, 0x4f, 0x4d, 0xa6, 0x15, 0x2d, 0x6f, 0x10, 0xaf, 0x71,
	0x0a, 0x63, 0x45, 0x36, 0x33, 0x79, 0xe5, 0x72, 0x5d, 0x2e, 0x2f, 0xd1, 0xaa, 0x75, 0xf8, 0xbb,
	0x07, 0xe3, 0xa3, 0xda, 0xcd, 0x3f, 0x93, 0x69, 0xf2, 0x8c, 0xf0, 0x1d, 0x0c, 0xbc, 0xc4, 0x9b,
	0x9e, 0xc7, 0xfe, 0xba, 0x1d, 0xf1, 0x39, 0xa3, 0x3b, 0x78, 0x02, 0x93, 0xaf, 0xfe, 0x18, 0xd2,
	0x51, 0x7b, 0xf4, 0x1b, 0xe1, 0xdb, 0xfe, 0xe6, 0x7c, 0xc4, 0x1f, 0x8b, 0x57, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0xea, 0x41, 0x45, 0xa7, 0x3a, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for AuthService service

type AuthServiceClient interface {
	Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error)
	ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error)
}

type authServiceClient struct {
	c           client.Client
	serviceName string
}

func NewAuthServiceClient(serviceName string, c client.Client) AuthServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "com.ta04.srv.auth"
	}
	return &authServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *authServiceClient) Auth(ctx context.Context, in *User, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "AuthService.Auth", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) ValidateToken(ctx context.Context, in *Token, opts ...client.CallOption) (*Token, error) {
	req := c.c.NewRequest(c.serviceName, "AuthService.ValidateToken", in)
	out := new(Token)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceHandler interface {
	Auth(context.Context, *User, *Token) error
	ValidateToken(context.Context, *Token, *Token) error
}

func RegisterAuthServiceHandler(s server.Server, hdlr AuthServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&AuthService{hdlr}, opts...))
}

type AuthService struct {
	AuthServiceHandler
}

func (h *AuthService) Auth(ctx context.Context, in *User, out *Token) error {
	return h.AuthServiceHandler.Auth(ctx, in, out)
}

func (h *AuthService) ValidateToken(ctx context.Context, in *Token, out *Token) error {
	return h.AuthServiceHandler.ValidateToken(ctx, in, out)
}
